# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b43195d2d9d252a77b4c35c097443922"
name = "whatsapp-chat-button\r"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
